### ISSUE TITLE
[Q] Will manipulation of DS_Store files be introduced anytime soon?

### ISSUE THREAD

**Issue by urwrstkn8mare** [sinistersnare/ds_store#5]
Hi I was just wondering if DS_Store manipulation will be worked on anytime soon. If so I'd be happy to help out. However, if it isn't I may rewrite a `.DS_Store` parser/manipulator from the ground up with [`binrw`](https://binrw.rs).

**Comment by sinistersnare** [comment]
TBH I have not touched this code in 4 years! Totally go ahead and work on whatever features you want! I would be happy if you wanted to become a maintainer on this and work on it, I could make you one.

**Comment by urwrstkn8mare** [comment]
Oh I see fair enough!

Thanks for the offer and quick replies but since I think I want to go about
it a different way I may rewrite it from the ground up.

**Comment by sinistersnare** [comment]
Thanks! I'm gonna close this and cut a new release.

**Comment by eugenesvk** [comment]
Are you aware of any of the implementations that allow writing to these `.DS_Store` files? I was wondering if maybe there could finally be a tool that is capable of accomplishing the simple task of trashing a few files properly... :) 

But as far as I undersood form various multi-year bug reports that's only possible if one would reimplement Finder's manipulation with the DS_Store stored in Trash https://github.com/Byron/trash-rs/discussions/123

**Comment by sinistersnare** [comment]
I haven't worked on this library in years, I have no context on any of this stuff.
